default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: tv_guide_development

test:
  <<: *default
  database: tv_guide_test

production:
  <<: *default
  database: tv_guide_production
  username: tv_guide
  password: <%= ENV['TV_GUIDE_DATABASE_PASSWORD'] %>
